### PR TITLE
Feature/rewind multipart retries

### PR DESCRIPTION
**Pull request by runningferret**
Merge in isakovp's fix for multipart. This should fix our 'infinite hang on multipart post (uploading a recording)' issue

See https://github.com/lostisland/faraday/pull/347 for some more.

### CODE REVIEW

**Comment by runningferret** [comment]
@sfgeorge @jared-prime for your reviewing pleasure

**Comment by sfgeorge** [comment]
What is commit 4c750bd?  Can we just merge [these 6 commits](https://github.com/isakovp/faraday/compare/cloudvox:ifbyphone-develop...isakovp:master) instead of 7?

**Comment by runningferret** [comment]
Isn't that just the merge commit? I just merged in the remote branch, is there some other, better way to handle this?

**Comment by sfgeorge** [comment]
Could we just open a PR using the green button that shows up on this here compare?

**Comment by sfgeorge** [comment]
[https://github.com/isakovp/faraday/compare/cloudvox:ifbyphone-develop...isakovp:master](https://github.com/isakovp/faraday/compare/cloudvox:ifbyphone-develop...isakovp:master)

**Pull request closed without merging**
