### PR TITLE
Feature/rewind multipart deux

### PR DESCRIPTION
**Pull request by runningferret**
Merge in isakovp's fix for multipart. This should fix our 'infinite hang on multipart post (uploading a recording)' issue

See https://github.com/lostisland/faraday/pull/347 for some more.

This is a different PR so we don't have a merge commit.

### CODE REVIEW

**Comment by runningferret** [comment]
@sfgeorge

**Comment by sfgeorge** [comment]
@runningferret Just noticed [0.9.1](https://github.com/lostisland/faraday/blob/master/CHANGELOG.md#v091) just came out.  Shall I update our base to that before merging this in?

**Comment by runningferret** [comment]
@sfgeorge Up to you... neither of those things in the changelog look particularly relevant to our usage so I doubt it's an issue either way.

**Comment by sfgeorge** [comment]
Reason I really mention is because lostisland/faraday#347 is no longer mergeable, and I'm afraid that 0.9.1 might be why.  Thinking on whether it may be good to resolve the conflict now, as supposed to having the pain later when it's no longer fresh in our minds.

**Pull request closed without merging**
